name: Claude
on:
  issue_comment:
    types:
      - created
jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.comment.body, '@Claude')
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
